# Generated by Django 3.2 on 2022-01-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_attendance_app', '0002_alter_staff_session_year_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
