# Generated by Django 3.2 on 2022-01-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_attendance_app', '0003_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancereport',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
